# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=50)),
                ('brand_contact', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Fs_usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fs_name', models.CharField(max_length=50)),
                ('fs_type', models.CharField(max_length=50)),
                ('server_id', models.IntegerField()),
                ('fs_usage', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ipaddress',
            fields=[
                ('ip_id', models.AutoField(primary_key=True, serialize=False)),
                ('ipaddress', models.GenericIPAddressField()),
                ('netmask', models.GenericIPAddressField()),
                ('gateway', models.GenericIPAddressField()),
                ('dns1', models.GenericIPAddressField()),
                ('dns2', models.GenericIPAddressField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('team', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('server_id', models.AutoField(primary_key=True, serialize=False)),
                ('fqdn', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('IN_PRD', 'In Production'), ('NOT_PRD', 'Not In Production')], max_length=10)),
                ('server_type', models.CharField(choices=[('VM', 'Virtual Machine'), ('HW', 'Hardware')], max_length=10)),
                ('nCPU', models.IntegerField()),
                ('CPU_t', models.CharField(max_length=10)),
                ('nRAM', models.IntegerField()),
                ('os_type', models.CharField(max_length=50)),
                ('os_ver', models.CharField(max_length=50)),
                ('backup_owner_id', models.IntegerField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Application')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Brands')),
                ('ip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Ipaddress')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Owners')),
            ],
        ),
        migrations.CreateModel(
            name='Sla',
            fields=[
                ('sla_id', models.IntegerField(primary_key=True, serialize=False)),
                ('response', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='servers',
            name='sla_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Sla'),
        ),
    ]
